spring.application.name=simple-pro
spring.datasource.url=jdbc:mysql://localhost:3306/simplepro
spring.datasource.username=root
spring.datasource.password=tharunsk4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true